apiVersion: v1
kind: ConfigMap
metadata:
  name: goldilocks-config-map
  namespace: kube-service
data:
  values.yaml: |-
    image:
      repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
      tag: v4.16.0
    vpa:
      enabled: true
      recommender:
        enabled: true
        extraArgs:
          v: "2"
          pod-recommendation-min-cpu-millicores: 15
          pod-recommendation-min-memory-mb: 100
        resources:
          requests:
            cpu: 50m
            memory: 300Mi
      updater:
        enabled: true
        extraArgs:
          min-replicas: 1
        resources:
          requests:
            cpu: 25m
            memory: 128Mi
          limits:
            memory: 256Mi
      admissionController:
        enabled: true
        resources:
          requests:
            cpu: 25m
            memory: 128Mi
          limits:
            memory: 256Mi
      metrics-server:
        enabled: false
    uninstallVPA: false
    controller:
      enabled: true
      logVerbosity: "1"
      flags:
        ignore-controller-kind: EphemeralRunner,EphemeralRunnerSet,AutoscalingListener,AutoscalingRunnerSet
      rbac:
        extraRules:
          - apiGroups: ["actions.github.com"]
            resources: ["ephemeralrunners", "ephemeralrunnersets", "autoscalinglisteners", "autoscalingrunnersets"]
            verbs: ["get", "list", "watch"]
      resources:
        requests:
          cpu: 25m
          memory: 128Mi
        limits:
          memory: 256Mi
    dashboard:
      enabled: true
      replicaCount: 1
      rbac:
        extraRules:
          - apiGroups: ["actions.github.com"]
            resources: ["ephemeralrunners", "ephemeralrunnersets", "autoscalinglisteners", "autoscalingrunnersets"]
            verbs: ["get", "list", "watch"]
      resources:
        requests:
          cpu: 25m
          memory: 128Mi
        limits:
          memory: 256Mi
