apiVersion: v1
kind: ConfigMap
metadata:
  name: clickstack-config-map
  namespace: monitoring
data:
  values.yaml: |-
    hyperdx:
      config:
        FRONTEND_URL: "https://hyperdx.hosted.fail"
      deployment:
        resources:
          requests:
            cpu: 150m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
    clickhouse:
      keeper:
        spec:
          replicas: 1
          dataVolumeClaimSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
      cluster:
        spec:
          containerTemplate:
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                cpu: "4"
                memory: 8Gi
          dataVolumeClaimSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
    mongodb:
      spec:
        members: 1
