apiVersion: v1
kind: Secret
metadata:
    name: clickstack-secrets
    namespace: monitoring
type: Opaque
stringData:
    hyperdx-api-key: ENC[AES256_GCM,data:lyZzbM5fz6DDrW45zEtTt+AFTW5wq9iTsEQw0Zff8dVPM5ALjrIvdOWs/br+ZaG5nhA34TZD/Zt6M3IG/d24WUvC,iv:WqzoM9ajuCd4HuJg0u4z7tSHZRXxR/XuUblTZs1FAHg=,tag:MDsiMlVMW1v6tMzUMGOeKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnY00zRmJMTHJpOFM5czR2
            NnZxZHIzU2NtUXcvUDJxOEk4UHpwMXdkcTN3Ck5KQmpvM1hNTEFHMXFVTS94L29H
            cEs5ZzdHQitnNi9wNjZhQ1o2bXNqcjgKLS0tIFoycGdFY3pITnZJbjFRQ3FvSWtI
            SWFOeGtSYTNVd0xWVGdGWHhOWVNQREUKjSWx4IleG36FSEJ37mtRGA7ZZQVQZllg
            cryqWffl6JxB/EMP7sXeTn9z5CaTl0q5ng9LAkEaQxsv3+uVKczG+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mvx2tgja4uztmjrdnfp5m2vlf3j7saj9lynzvyauhmrjvkzu2u4s7sf387
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T03:42:08Z"
    mac: ENC[AES256_GCM,data:ZTb9iy45YOQAHFWTNiq1KFlaod0aDLYSoIWDD1kEV8Cjcxi2xkBvOTHxlbyr8ucXCnkl1r+WrpsmNDZEI3cwKsWhohSsMur6wG/i6pS2YlNhsv4/Lg6ROw6dNTWYYWQUnkAEwBbNr0kxubNv3UeKnRhMZttUFBxwiDfq0R/+koY=,iv:dszUJL/bhRn6/3WwTq97yj3PC5ST1iFSl9WKtWXy7Yc=,tag:9XXGKV8F8Xx0EaxYN6tBgw==,type:str]
    version: 3.13.3
