apiVersion: v1
kind: Secret
metadata:
    name: clickstack-secrets
    namespace: monitoring
type: Opaque
stringData:
    hyperdx-api-key: ENC[AES256_GCM,data:UNCSILqaWStCWY9IN15LPS6rsePjfM/fZOYgkq/jVJfpmX3E,iv:lMZvdh5b7WrvA5jpc08bMuvr2PVblDQR+P41iBPrsYA=,tag:7rYAfnwq/CJ81mQwu7pLSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WHpBM1ZoKzJ1bnpYK1gy
            dTg5MTd4MkJuaWsrMmlNaitCMVBPbGVSaVE0CnlUa0lZUlBEVGlmajNIakZoL3Va
            SnpONUVPNmRxT0JEa0wzR1ZPckxrM3MKLS0tIEc2OW9VNSticHV2dzNOZG1FVU0z
            VVZMVGxkbk1ieG5TakJYYTY5dWI1T1kKtoirPnJornh4v9AbbMEJod2h0ualJU9e
            e1LV6Zut8D66FfXtS8MZFkJVgi8wIJ3v0KA4Q/PtNV9gc25SMKdryw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mvx2tgja4uztmjrdnfp5m2vlf3j7saj9lynzvyauhmrjvkzu2u4s7sf387
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T12:57:02Z"
    mac: ENC[AES256_GCM,data:LUwYqnqqRiHqSLgJ+zqNbraSauuGzrGoXXIC9m/qO55Qquaq+UKWbbpOsuI5/+d4sE2JtoShfLqlwVEW47G/0mCT0kprSuTEp61G1Moz1oGC+jzmuiddBCRKLl3Wfrjv4crLkXXl7F/Lwrm5mUJTXpvlmjL/70/yP4+vfvc/BlY=,iv:a5xUqnJXHFFxHNnlidMzYwx75kunWYoGPmxC5D5+K/4=,tag:s9RStavjkwr0sMbtHnnuzA==,type:str]
    version: 3.13.3
