apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secrets
    namespace: development
type: Opaque
stringData:
    RUNNER_SECRET: ENC[AES256_GCM,data:XaEEHnwTLEkm1IVKlCFuMJKl+/49TbWxcihnYr+V12cqEpEv3dE+2w==,iv:4eaM+APvCZRWQjMg0V+00/aHlbmklJmeLm98pSP+5Sg=,tag:/XBBUuxCMC1qr5+gqDOK3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXL3kvdFdHSXNHb09Ca01C
            T1EvM1M2TGp1d0hDWHpTOXU4Q0JkbE5lRGo0CnhSUG9FcmVWNWhldHA2dVFCSGFn
            RGRqanF5clN2R0k0Q0hlY0ZhSnFxc3cKLS0tIGozSVNVdjEzc0dMN1Y3V2QrM3RC
            VkpMR3VGMVhoV2w0NW8wRlVtMGpKazgKw3GMui66bdpdxaJzNlFD/HtuCo5gHTKh
            ce9Hcxzln2t2AmSQ2VZo9ybcvU+o+/9VA1gMooMouIeOwvmUDXc7sg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mvx2tgja4uztmjrdnfp5m2vlf3j7saj9lynzvyauhmrjvkzu2u4s7sf387
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T18:55:59Z"
    mac: ENC[AES256_GCM,data:jMoWTSojrkjSAlSSfCFxUYTpk7X2zsr80uYZO0cPzXl8RDtB8JzrlNmtwUSTyrR/doY6+xcYbpNF9sR3Z2JhaYcNTRapN3c5sS/nALK13cW06r+rNgzii9Ogj9TQOV+1465R3LcCP3TbIu/bPh85UGyF2b6GRvYM100tJfb15uo=,iv:OJSZ8LkwazPFR7G696pIpxXpY0TaU67HNJ2D8sGGhYE=,tag:t/hDFIe60FfchiaiTIvP1Q==,type:str]
    version: 3.13.3
