apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  namespace: security
  labels:
    app.kubernetes.io/name: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-rwo
  resources:
    requests:
      storage: 8Gi
