apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:0aOOgTPlae3sBSLehXd7abAgxHKAYN6Kxe2hyRHEpoxnaIiY/FfbndfAzRrHRvXYaqkkpcLfjUiym4M7oM9ZIkLANkvGtUfcoQNTcz0DUyBeRm8pzTEGbFxO78HycVY1bVo7h++6F4DF9LrQan9xaCvRHojqSw==,iv:RO4bbZ6CDcfMRcKiiocn+Dxu3XpjTq5jzj8pt49TBWk=,tag:koHTAq1/86JylJxkrphT0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGN1UvT3R6LzlPM29qQVJv
            QkU3dzRDOUR3ZGNQQmlYaXczeFVCbDVWOXljCkJwdytQN05lTnBXNmJIV1ovREV5
            VkxJcWUrZDRWVXNIODlqZThiOE5sMzQKLS0tIFljcjhSVEQrVFdZcUNuUTJxSlZX
            YVdrZ1ZoNng4V25raDh0OCtQcStnelkKtKqfrnaV+Ewmrn/jw8naNwXi9egN+5yW
            D3/1IOn/t7Durzrdmwk3OhNahP76NGdaw3841DJ0ZgjNizQwbXYyRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mvx2tgja4uztmjrdnfp5m2vlf3j7saj9lynzvyauhmrjvkzu2u4s7sf387
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T17:32:58Z"
    mac: ENC[AES256_GCM,data:CBL5AO8cy06l8IVmEq/cF/f1M2DKC183Nl64fLdnYYrByKKh5ao+17GCWdF4fsIqhgHUTIraLfb6AUAONyGAJDJoSVAwTzyhDjwQFDXiJqZkjQ5cd86DholZZxHSp5c9Hz2BJRqZ0oD74z9ZT8H3ipraZWikS/om2/mswM87PiI=,iv:gtZoM4YgAj+QIPxJFMvt+Tug7j5+WhkYCu0DF/gNKjU=,tag:RWF61LgUZxOj79n5ZEqh/w==,type:str]
    version: 3.13.1
