apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  namespace: media
  labels:
    app.kubernetes.io/name: nzbget
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/egress: wireguard
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nzbget
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nzbget
        app.kubernetes.io/managed-by: flux
        app.kubernetes.io/egress: wireguard
    spec:
      runtimeClassName: youki
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      automountServiceAccountToken: false
      initContainers:
        - name: init-nzbget
          # renovate: datasource=docker depName=docker.io/busybox
          image: docker.io/busybox:1.38.0@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
          imagePullPolicy: IfNotPresent
          command: ["sh","-c"]
          args:
            - |
              set -e
              echo "[init] pre-creating folder tree and fixing ownership"
              mkdir -p /init/downloads/complete /init/downloads/incomplete
              mkdir -p /init/media/movies /init/media/tvshows /init/media/leaving-soon
              chown -R 1000:1000 /init
              chmod -R 775 /init
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: media
              mountPath: /init
      containers:
        - name: nzbget
          # renovate: datasource=docker depName=lscr.io/linuxserver/nzbget
          image: lscr.io/linuxserver/nzbget:latest@sha256:1dca6a4407e08313919d2780bf2a6bc17e21b947a6e8e34624b9e115795fcf8c
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 6789
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "2000m"
              memory: "4096Mi"
              ephemeral-storage: "20Gi"
          livenessProbe:
            tcpSocket:
              port: 6789
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 6789
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /downloads
              subPath: downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: nzbget-config
        - name: media
          persistentVolumeClaim:
            claimName: media
