apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manga-config
  namespace: media
  labels:
    app.kubernetes.io/name: manga
    app.kubernetes.io/managed-by: flux
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-rwo
  resources:
    requests:
      storage: 8Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manga-media
  namespace: media
  labels:
    app.kubernetes.io/name: manga
    app.kubernetes.io/managed-by: flux
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-rwo
  resources:
    requests:
      storage: 20Gi
