apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizarr
  namespace: media
  labels:
    app.kubernetes.io/name: wizarr
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: wizarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wizarr
        app.kubernetes.io/managed-by: flux
    spec:
      runtimeClassName: youki
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: wizarr
          # renovate: datasource=docker depName=ghcr.io/wizarrrr/wizarr
          image: ghcr.io/wizarrrr/wizarr:latest@sha256:0627e8e13f0fa76ab3a0348153bdcba5083c9f86745299a81394b8099900758e
          imagePullPolicy: IfNotPresent
          env:
            - name: DISABLE_BUILTIN_AUTH
              value: "true"
            - name: UV_CACHE_DIR
              value: /tmp/.uv_cache
          ports:
            - containerPort: 5690
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2048Mi"
              ephemeral-storage: "5Gi"
          livenessProbe:
            tcpSocket:
              port: 5690
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 5690
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /data/database
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: wizarr-config
