apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tinyauth-data
  namespace: security
  labels:
    app.kubernetes.io/name: tinyauth
    app.kubernetes.io/managed-by: flux
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-rwo
  resources:
    requests:
      storage: 1Gi
