apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelfmark
  namespace: media
  labels:
    app.kubernetes.io/name: shelfmark
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/egress: wireguard
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: shelfmark
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shelfmark
        app.kubernetes.io/managed-by: flux
        app.kubernetes.io/egress: wireguard
    spec:
      runtimeClassName: youki
      initContainers:
        - name: init-log-perms
          image: busybox:1.37@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
          command:
            - sh
            - -c
            - |
              mkdir -p /var/log/shelfmark && chown -R 1000:1000 /var/log/shelfmark
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      automountServiceAccountToken: false
      containers:
        - name: shelfmark
          # renovate: datasource=docker depName=ghcr.io/calibrain/shelfmark-lite
          image: ghcr.io/calibrain/shelfmark-lite:latest@sha256:4ad01124a82d58a538bf4a05214617c5bd06fe88aac4ffb865bf654f04fcac99
          imagePullPolicy: IfNotPresent
          env:
            - name: EXT_BYPASSER_URL
              value: "http://flaresolverr:8191"
          ports:
            - containerPort: 8084
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2048Mi"
              ephemeral-storage: "5Gi"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /downloads
              subPath: downloads
            - name: media
              mountPath: /books
              subPath: media/books
            - name: log
              mountPath: /var/log/shelfmark
      volumes:
        - name: log
          emptyDir: {}
        - name: config
          persistentVolumeClaim:
            claimName: shelfmark-config
        - name: media
          persistentVolumeClaim:
            claimName: media
