apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor-browser
  namespace: tor
  labels:
    app.kubernetes.io/name: tor-browser
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/egress: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tor-browser
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tor-browser
        app.kubernetes.io/managed-by: flux
        app.kubernetes.io/egress: wireguard
    spec:
      automountServiceAccountToken: false
      containers:
        - name: tor-browser
          # renovate: datasource=docker depName=domistyle/tor-browser
          image: docker.io/domistyle/tor-browser:15.0.8@sha256:a62d993c0135df15a610c2e35c72abee30bfa5857e4c51a7896bb80ea9181207
          imagePullPolicy: IfNotPresent
          env:
            - name: DISPLAY_WIDTH
              value: "1366"
            - name: DISPLAY_HEIGHT
              value: "768"
          ports:
            - name: http
              containerPort: 5800
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
              ephemeral-storage: "5Gi"
          securityContext:
            readOnlyRootFilesystem: false
