apiVersion: v1
kind: Service
metadata:
  name: tor-browser
  namespace: tor
  labels:
    app.kubernetes.io/name: tor-browser
    app.kubernetes.io/managed-by: flux
spec:
  selector:
    app.kubernetes.io/name: tor-browser
  ports:
    - port: 5800
      targetPort: 5800
      protocol: TCP
      name: https
  type: ClusterIP
