apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: default
  labels:
    app.kubernetes.io/name: homeassistant
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: homeassistant
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homeassistant
        app.kubernetes.io/managed-by: flux
    spec:
      runtimeClassName: youki
      automountServiceAccountToken: false
      containers:
        - name: homeassistant
          # renovate: datasource=docker depName=lscr.io/linuxserver/homeassistant
          image: lscr.io/linuxserver/homeassistant:latest@sha256:eed76dc0d5fea6853940af1b704f0399024f497a1349ebbe57e4cdcf6a45475b
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8123
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8123
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8123
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
              ephemeral-storage: "5Gi"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homeassistant-config
