apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-config-map
  namespace: security
data:
  values.yaml: |-
    driver:
      enabled: true
      kind: modern_ebpf
    collectors:
      enabled: true
      kubernetes:
        enabled: false
      containerEngine:
        enabled: true
        engines:
          docker:
            enabled: false
          podman:
            enabled: false
          containerd:
            enabled: false
          lxc:
            enabled: false
          libvirt_lxc:
            enabled: false
          bpm:
            enabled: false
          cri:
            enabled: true
            sockets:
              - /run/containerd/containerd.sock
    controller:
      kind: daemonset
    falcoctl:
      artifact:
        install:
          enabled: true
        follow:
          enabled: true
      config:
        artifact:
          install:
            refs: [falco-rules:5, k8saudit-rules:0.11, k8saudit:0.11]
          follow:
            refs: [falco-rules:5, k8saudit-rules:0.11]
    services:
      - name: k8saudit-webhook
        type: ClusterIP
        ports:
          - port: 9765
            protocol: TCP
    falco:
      json_output: true
      rules_files:
        - /etc/falco/falco_rules.yaml
        - /etc/falco/falco_rules.local.yaml
        - /etc/falco/k8s_audit_rules.yaml
        - /etc/falco/rules.d
      metrics:
        enabled: true
        interval: "1h"
        output_rule: true
        output_file: /tmp/falco_stats.json
        resource_utilization_enabled: true
        state_counters_enabled: true
        kernel_event_counters_enabled: true
        libbpf_stats_enabled: true
        plugins_metrics_enabled: true
      plugins:
        - name: k8saudit
          library_path: libk8saudit.so
          init_config:
            ""
          open_params: "http://:9765/k8s-audit"
        - name: json
          library_path: libjson.so
          init_config: ""
      load_plugins: [k8saudit, json]
